<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<OutputType>WinExe</OutputType>
	<TargetFramework>net10.0-windows</TargetFramework>
	<UseWPF>true</UseWPF>
	<Nullable>enable</Nullable>
	<ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
	<ProjectReference Include="..\libs\EvaluationLib\EvaluationLib.csproj" />
	<ProjectReference Include="..\libs\MemoryLib\MemoryLib.csproj" />
	<ProjectReference Include="..\libs\InfoLib\InfoLib.csproj" />
  </ItemGroup>

</Project>
